got rid of extra file for useradd

diff --git a/do-userdata b/do-userdata
--- a/do-userdata
+++ b/do-userdata
@@ -1,18 +1,25 @@
-
 #!/bin/bash
 #just copy the content of this file into the userdata window of Digital Ocean droplet when creating it.
 #update user name and password to your own.
-username=my-username
-password=my-p@ssw0rd!
-cd /opt/
-curl -O curl -O https://raw.githubusercontent.com/sjoulaei/simpledotsys/master/add_super_user.sh
-chmod u+x add_super_user.sh
-sh add_super_user.sh $username $password
+user=saeed
+password=ch@ngeTHI$p@ssw0rd!
+name="Saeed Joulaei"
+
+useradd "$user" -c "$name"
+
+echo $user:$password | chpasswd
+usermod -aG wheel $user
+
+#make it nopassword for sudo
+echo -e "\033[32mupdate visudo to NOPASSWORD for wheel group\033[0m"
+sed -i "$ a ## Next Line Added by simpledotsys" /etc/sudoers
+sed -i "$ a $user ALL=(ALL)       NOPASSWD: ALL" /etc/sudoers && echo 'sudoers updated Successfully' || echo 'sudoers update failed'
+
 
 yum -y install git
 
-su $username <<EOF
-cd /home/$username/
+su $user <<EOF
+cd /home/$user/
 git clone https://github.com/sjoulaei/simpledotsys.git
 cd simpledotsys
 sh install.sh
